//! # Differential Fuzzing Tests — `diff_tests.rs`  (#189)
//!
//! This module implements **differential property-based testing** between:
//!
//! * **Reference**: pure functions in `core.rs` — no Env, no SDK, plain slices.
//! * **Subject**: Soroban-SDK-Vec-based functions in `storage.rs` — the actual
//!   contract implementations operating on `soroban_sdk::Vec<i128>`.
//!
//! ## How it works
//!
//! For every random input generated by proptest, both implementations are
//! exercised with the **same** values. The outputs must be **bit-for-bit
//! identical**. Any divergence would reveal a bug in one of the paths.
//!
//! ## Coverage
//!
//! | Property | Core fn | Storage fn |
//! |---|---|---|
//! | Median (odd/even/mixed) | `median_core` | `compute_median` |
//! | Arithmetic mean | `mean_core` | `compute_mean` |
//! | Trimmed mean (10 %) | `trimmed_mean_core` | `compute_trimmed_mean` |
//! | Weighted median (uniform weights) | `weighted_median_core` | `compute_weighted_median` |
//! | Weighted median (random weights) | `weighted_median_core` | `compute_weighted_median` |
//! | Quickselect k-th smallest | `quickselect_core` | (sort + index verify) |
//!
//! ## Running
//!
//! ```sh
//! cargo test -p price-oracle --lib diff_tests
//! ```
//!
//! Increase `PROPTEST_CASES` for deeper coverage:
//! ```sh
//! PROPTEST_CASES=100000 cargo test -p price-oracle --lib diff_tests
//! ```

#![cfg(test)]

use proptest::prelude::*;
use soroban_sdk::Env;

use crate::core_pricing::{
    mean_core, median_core, quickselect_core, trimmed_mean_core, weighted_median_core,
};
use crate::storage::{compute_mean, compute_median, compute_trimmed_mean, compute_weighted_median};

// ────────────────────────────────────────────────────────────────────────────
// Helpers
// ────────────────────────────────────────────────────────────────────────────

/// Copy a `&[i128]` into a `soroban_sdk::Vec<i128>`.
fn to_sdk_vec(env: &Env, s: &[i128]) -> soroban_sdk::Vec<i128> {
    let mut v = soroban_sdk::Vec::new(env);
    for &x in s {
        v.push_back(x);
    }
    v
}

// ────────────────────────────────────────────────────────────────────────────
// Proptest strategies
// ────────────────────────────────────────────────────────────────────────────

/// A vector of 1–50 `i128` values derived from `i64` to stay well inside
/// `i128` range while still exercising large numbers.
fn price_vec() -> impl Strategy<Value = Vec<i128>> {
    proptest::collection::vec(any::<i64>().prop_map(|x| x as i128), 1..=50usize)
}

/// A pair of equal-length price and weight vectors (weights clamped [1,100]).
fn price_weight_pair() -> impl Strategy<Value = (Vec<i128>, Vec<i128>)> {
    (1..=50usize).prop_flat_map(|n| {
        let prices = proptest::collection::vec(any::<i64>().prop_map(|x| x as i128), n);
        let weights = proptest::collection::vec(1i128..=100i128, n);
        (prices, weights)
    })
}

// ────────────────────────────────────────────────────────────────────────────
// Differential: Median
// ────────────────────────────────────────────────────────────────────────────

proptest! {
    #![proptest_config(ProptestConfig::with_cases(2000))]

    /// `median_core` and `compute_median` must agree on every input.
    #[test]
    fn diff_median(prices in price_vec()) {
        let env = Env::default();
        let sdk_vec = to_sdk_vec(&env, &prices);
        let core_result = median_core(&prices);
        let sdk_result  = compute_median(&sdk_vec);
        prop_assert_eq!(
            core_result,
            sdk_result,
            "median divergence on {:?}: core={}, sdk={}",
            &prices[..prices.len().min(8)], core_result, sdk_result
        );
    }

    /// `mean_core` and `compute_mean` must agree on every input.
    #[test]
    fn diff_mean(prices in price_vec()) {
        let env = Env::default();
        let sdk_vec = to_sdk_vec(&env, &prices);
        let core_result = mean_core(&prices);
        let sdk_result  = compute_mean(&sdk_vec);
        prop_assert_eq!(
            core_result,
            sdk_result,
            "mean divergence on {:?}: core={}, sdk={}",
            &prices[..prices.len().min(8)], core_result, sdk_result
        );
    }

    /// `trimmed_mean_core(_, 10)` and `compute_trimmed_mean(_, 10)` must agree.
    #[test]
    fn diff_trimmed_mean(prices in price_vec()) {
        let env = Env::default();
        let sdk_vec = to_sdk_vec(&env, &prices);
        let core_result = trimmed_mean_core(&prices, 10);
        let sdk_result  = compute_trimmed_mean(&sdk_vec, 10);
        prop_assert_eq!(
            core_result,
            sdk_result,
            "trimmed_mean divergence on {:?}: core={}, sdk={}",
            &prices[..prices.len().min(8)], core_result, sdk_result
        );
    }

    /// `weighted_median_core` and `compute_weighted_median` must agree on
    /// equal-length price/weight pairs.
    #[test]
    fn diff_weighted_median((prices, weights) in price_weight_pair()) {
        let env = Env::default();
        let sdk_prices  = to_sdk_vec(&env, &prices);
        let sdk_weights = to_sdk_vec(&env, &weights);
        let core_result = weighted_median_core(&prices, &weights);
        let sdk_result  = compute_weighted_median(&sdk_prices, &sdk_weights);
        prop_assert_eq!(
            core_result,
            sdk_result,
            "weighted_median divergence: core={}, sdk={}",
            core_result, sdk_result
        );
    }

    /// Weighted median with uniform weights must equal the unweighted median.
    #[test]
    fn diff_weighted_median_uniform(prices in price_vec()) {
        let env = Env::default();
        let n = prices.len();
        let weights: Vec<i128> = vec![50i128; n];
        let sdk_prices  = to_sdk_vec(&env, &prices);
        let sdk_weights = to_sdk_vec(&env, &weights);
        let wm_core   = weighted_median_core(&prices, &weights);
        let wm_sdk    = compute_weighted_median(&sdk_prices, &sdk_weights);
        let med_core  = median_core(&prices);
        let med_sdk   = compute_median(&sdk_vec_of(&env, &prices));
        // Core and SDK weighted median must agree.
        prop_assert_eq!(wm_core, wm_sdk);
        // Weighted median with uniform weights must equal unweighted median.
        prop_assert_eq!(
            wm_core, med_core,
            "uniform-weight wm != median: wm={}, median={}, prices={:?}",
            wm_core, med_core, &prices[..prices.len().min(8)]
        );
        prop_assert_eq!(wm_sdk, med_sdk);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Quickselect correctness properties
    // ─────────────────────────────────────────────────────────────────────────

    /// quickselect_core places the k-th smallest element at position k.
    /// Verified by comparing with a fully sorted copy.
    #[test]
    fn quickselect_kth_correct(
        mut prices in proptest::collection::vec(any::<i64>().prop_map(|x| x as i128), 1..=50usize),
        k_raw in any::<usize>(),
    ) {
        let n = prices.len();
        let k = k_raw % n;
        let mut sorted = prices.clone();
        sorted.sort_unstable();
        quickselect_core(&mut prices, k);
        prop_assert_eq!(
            prices[k],
            sorted[k],
            "quickselect k={} gave {} but sorted[k]={}", k, prices[k], sorted[k]
        );
    }

    /// After quickselect for k, all elements in prices[..k] are ≤ prices[k].
    #[test]
    fn quickselect_partition_invariant(
        mut prices in proptest::collection::vec(any::<i64>().prop_map(|x| x as i128), 2..=50usize),
        k_raw in any::<usize>(),
    ) {
        let n = prices.len();
        let k = k_raw % n;
        quickselect_core(&mut prices, k);
        let pivot = prices[k];
        for &v in &prices[..k] {
            prop_assert!(v <= pivot, "partition violated: {} > pivot={} at k={}", v, pivot, k);
        }
        for &v in &prices[k+1..] {
            prop_assert!(v >= pivot, "partition violated: {} < pivot={} at k={}", v, pivot, k);
        }
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Helper used inside proptest closure (avoids borrow-checker conflict)
// ────────────────────────────────────────────────────────────────────────────
fn sdk_vec_of(env: &Env, prices: &[i128]) -> soroban_sdk::Vec<i128> {
    to_sdk_vec(env, prices)
}

// ────────────────────────────────────────────────────────────────────────────
// Additional deterministic (non-proptest) differential smoke tests
// ────────────────────────────────────────────────────────────────────────────

#[test]
fn smoke_median_single_element() {
    let env = Env::default();
    let prices = [42i128];
    assert_eq!(median_core(&prices), compute_median(&to_sdk_vec(&env, &prices)));
}

#[test]
fn smoke_median_two_elements() {
    let env = Env::default();
    let prices = [10i128, 30];
    assert_eq!(median_core(&prices), compute_median(&to_sdk_vec(&env, &prices)));
}

#[test]
fn smoke_median_sorted_odd() {
    let env = Env::default();
    let prices = [1i128, 2, 3, 4, 5];
    assert_eq!(median_core(&prices), compute_median(&to_sdk_vec(&env, &prices)));
}

#[test]
fn smoke_median_sorted_even() {
    let env = Env::default();
    let prices = [1i128, 2, 3, 4];
    assert_eq!(median_core(&prices), compute_median(&to_sdk_vec(&env, &prices)));
}

#[test]
fn smoke_median_reverse_sorted() {
    let env = Env::default();
    let prices = [50i128, 40, 30, 20, 10];
    assert_eq!(median_core(&prices), compute_median(&to_sdk_vec(&env, &prices)));
}

#[test]
fn smoke_mean_basic() {
    let env = Env::default();
    let prices = [10i128, 20, 30];
    assert_eq!(mean_core(&prices), compute_mean(&to_sdk_vec(&env, &prices)));
}

#[test]
fn smoke_weighted_median_known_result() {
    let env = Env::default();
    // 3 sources: prices [100, 200, 300], weights [10, 80, 10]
    // Sorted: (100,10),(200,80),(300,10). total=100, half=50.
    // cumulative after (100,10) = 10 ≤ 50; after (200,80) = 90 > 50 → median = 200.
    let prices  = [100i128, 300, 200];
    let weights = [10i128, 10, 80];
    let expected = 200i128;
    assert_eq!(weighted_median_core(&prices, &weights), expected);
    assert_eq!(
        compute_weighted_median(&to_sdk_vec(&env, &prices), &to_sdk_vec(&env, &weights)),
        expected,
    );
}

#[test]
fn smoke_weighted_median_low_rep_outlier() {
    let env = Env::default();
    // Outlier at 1_000_000 has reputation 1; honest sources have rep 90.
    let prices  = [100i128, 102, 1_000_000, 101];
    let weights = [90i128, 90, 1, 90];
    let core_v = weighted_median_core(&prices, &weights);
    let sdk_v  = compute_weighted_median(
        &to_sdk_vec(&env, &prices),
        &to_sdk_vec(&env, &weights),
    );
    assert_eq!(core_v, sdk_v, "weighted_median implementations disagree");
    // The result should be in the honest cluster [100,102], not near the outlier.
    assert!(
        core_v <= 102,
        "expected weighted_median close to honest cluster, got {}",
        core_v
    );
}

#[test]
fn smoke_weighted_median_all_equal_prices() {
    let env = Env::default();
    let prices  = [500i128; 7];
    let weights = [10i128, 20, 30, 40, 50, 60, 70];
    assert_eq!(
        weighted_median_core(&prices, &weights),
        compute_weighted_median(&to_sdk_vec(&env, &prices), &to_sdk_vec(&env, &weights)),
    );
}
