#!/usr/bin/env python3
"""Generate the machine-readable error registry from errors.rs (issue #537).

Usage: gen_error_registry.py [--check]
  --check  fail if generated output differs from committed files, if any code
           lacks remediation, or if a previously published code was removed or
           renumbered (compared against docs/errors/errors.lock.json).
"""
import json, re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "contracts/price-oracle/src/errors.rs"
REM = ROOT / "docs/errors/remediation.json"
OUT_JSON = ROOT / "docs/errors/registry.json"
OUT_MD = ROOT / "docs/errors/REGISTRY.md"
LOCK = ROOT / "docs/errors/errors.lock.json"


def parse():
    body = SRC.read_text().split("pub enum ErrorCode", 1)[1]
    codes, doc = [], []
    for line in body.splitlines():
        s = line.strip()
        if s.startswith("///"):
            doc.append(s[3:].strip())
        elif m := re.match(r"(\w+)\s*=\s*(\d+),", s):
            codes.append({"code": int(m[2]), "name": m[1], "meaning": " ".join(doc)})
            doc = []
        elif s.startswith("//") or not s:
            doc = [] if not s.startswith("///") else doc
    return sorted(codes, key=lambda c: c["code"])


def main():
    check = "--check" in sys.argv
    rem = json.loads(REM.read_text())
    entries, errors = [], []
    for c in parse():
        r = rem.get(c["name"])
        if not r or not r.get("cause") or not r.get("remediation") or r.get("class") not in ("config", "caller", "transient", "state"):
            errors.append(f"missing/invalid remediation for {c['name']} ({c['code']})")
            r = r or {}
        entries.append({**c, "class": r.get("class"), "cause": r.get("cause"), "remediation": r.get("remediation")})
    names = {e["name"] for e in entries}
    errors += [f"stale remediation entry {n}" for n in rem if n not in names]
    published = json.loads(LOCK.read_text()) if LOCK.exists() else {}
    by_name = {e["name"]: e["code"] for e in entries}
    for name, code in published.items():
        if name not in by_name:
            errors.append(f"published code {name}={code} was removed")
        elif by_name[name] != code:
            errors.append(f"published code {name} renumbered {code} -> {by_name[name]}")
    taken = {code: name for name, code in published.items()}
    errors += [f"code {e['code']} reused by {e['name']} (was {taken[e['code']]})"
               for e in entries if taken.get(e["code"], e["name"]) != e["name"]]

    reg = json.dumps({"contract": "price-oracle", "errors": entries}, indent=2) + "\n"
    md = ["# Error Registry (generated)\n", "> Generated by `scripts/devx/gen_error_registry.py` from `errors.rs` + `remediation.json`. Do not edit.\n",
          "| Code | Name | Class | Meaning | Cause | Remediation |", "|---|---|---|---|---|---|"]
    md += [f"| {e['code']} | <a id=\"e{e['code']}\"></a>`{e['name']}` | {e['class']} | {e['meaning']} | {e['cause']} | {e['remediation']} |" for e in entries]
    md = "\n".join(md) + "\n"
    lock = {**published, **by_name}
    lock = json.dumps(dict(sorted(lock.items(), key=lambda kv: kv[1])), indent=2) + "\n"

    if check:
        for p, want in ((OUT_JSON, reg), (OUT_MD, md), (LOCK, lock)):
            if not p.exists() or p.read_text() != want:
                errors.append(f"{p.relative_to(ROOT)} is out of date; run scripts/devx/gen_error_registry.py")
    else:
        OUT_JSON.write_text(reg); OUT_MD.write_text(md); LOCK.write_text(lock)
    if errors:
        print("\n".join(errors), file=sys.stderr); sys.exit(1)
    print(f"error registry OK ({len(entries)} codes)")


if __name__ == "__main__":
    main()
