"""AUTO-GENERATED by sdk/codegen/generate.py from sdk/codegen/abi.json — DO NOT EDIT."""
from typing import Any, Callable, List, Optional

ABI_VERSION = "1.0.0"

Asset = Any
PriceData = Any
StagedConfig = Any


class OracleBindings:
    def __init__(self, invoke: Callable[[str, list], Any]) -> None:
        self._invoke = invoke

    def decimals(self) -> int:
        return self._invoke("decimals", [])

    def base(self) -> Asset:
        return self._invoke("base", [])

    def lastprice(self, asset: Asset) -> Optional[PriceData]:
        return self._invoke("lastprice", [asset])

    def price(self, asset: Asset, timestamp: int) -> Optional[PriceData]:
        return self._invoke("price", [asset, timestamp])

    def prices(self, asset: Asset, records: int) -> Optional[List[PriceData]]:
        return self._invoke("prices", [asset, records])

    def get_effective_config(self, asset: str) -> StagedConfig:
        return self._invoke("get_effective_config", [asset])
