"""Generate SDK bindings from the contract ABI (#534).

Source of truth: ``sdk/codegen/abi.json`` (a snapshot of the contract
interface, refreshed from the built WASM via scripts/generate-abi.sh).
Generated files must never be edited by hand.

    python -m sdk.codegen.generate            # regenerate all languages
    python -m sdk.codegen.generate --check    # CI drift gate: exit 1 on drift

``--check`` fails when (a) a committed binding differs from what the ABI
generates, or (b) an ABI function no longer exists as a ``pub fn`` in
contracts/price-oracle/src/lib.rs.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Callable, Dict, List

ROOT = Path(__file__).resolve().parents[2]
ABI = ROOT / "sdk/codegen/abi.json"
LIB_RS = ROOT / "contracts/price-oracle/src/lib.rs"
HEADER = "AUTO-GENERATED by sdk/codegen/generate.py from sdk/codegen/abi.json — DO NOT EDIT."

TS_TYPES = {"u32": "number", "u64": "bigint", "i128": "bigint", "bool": "boolean",
            "Address": "string", "Symbol": "string"}
PY_TYPES = {"u32": "int", "u64": "int", "i128": "int", "bool": "bool",
            "Address": "str", "Symbol": "str"}


def _map(t: str, table: Dict[str, str], opt: str, vec: str) -> str:
    m = re.fullmatch(r"(Option|Vec)<(.+)>", t)
    if m:
        inner = _map(m.group(2), table, opt, vec)
        return (opt if m.group(1) == "Option" else vec).format(inner)
    return table.get(t, t)


def ts_type(t: str) -> str:
    return _map(t, TS_TYPES, "{} | null", "{}[]")


def py_type(t: str) -> str:
    return _map(t, PY_TYPES, "Optional[{}]", "List[{}]")


def camel(name: str) -> str:
    head, *rest = name.split("_")
    return head + "".join(p.title() for p in rest)


def gen_typescript(abi: dict) -> str:
    out = [f"// {HEADER}", f"export const ABI_VERSION = \"{abi['abi_version']}\";", "",
           "export interface Invoker {", "  invoke(method: string, args: unknown[]): Promise<unknown>;", "}", "",
           "export class OracleBindings {", "  constructor(private readonly invoker: Invoker) {}"]
    for f in abi["functions"]:
        params = ", ".join(f"{p['name']}: {ts_type(p['type'])}" for p in f["inputs"])
        names = ", ".join(p["name"] for p in f["inputs"])
        out += ["", f"  async {camel(f['name'])}({params}): Promise<{ts_type(f['output'])}> {{",
                f"    return (await this.invoker.invoke(\"{f['name']}\", [{names}])) as {ts_type(f['output'])};",
                "  }"]
    return "\n".join(out + ["}", ""])


def gen_python(abi: dict) -> str:
    out = [f'"""{HEADER}"""', "from typing import Any, Callable, List, Optional", "",
           f'ABI_VERSION = "{abi["abi_version"]}"', "", "Asset = Any", "PriceData = Any", "StagedConfig = Any",
           "", "", "class OracleBindings:",
           "    def __init__(self, invoke: Callable[[str, list], Any]) -> None:",
           "        self._invoke = invoke"]
    for f in abi["functions"]:
        params = "".join(f", {p['name']}: {py_type(p['type'])}" for p in f["inputs"])
        names = ", ".join(p["name"] for p in f["inputs"])
        out += ["", f"    def {f['name']}(self{params}) -> {py_type(f['output'])}:",
                f"        return self._invoke(\"{f['name']}\", [{names}])"]
    return "\n".join(out + [""])


TARGETS: Dict[str, Callable[[dict], str]] = {
    "sdk/typescript/src/generated/bindings.ts": gen_typescript,
    "sdk/python/oracle_sdk/generated_bindings.py": gen_python,
}


def drift(abi: dict, root: Path = ROOT, lib_rs: Path = LIB_RS) -> List[str]:
    problems = []
    for rel, gen in TARGETS.items():
        path = root / rel
        if not path.exists() or path.read_text() != gen(abi):
            problems.append(f"{rel} is out of date with sdk/codegen/abi.json")
    src = lib_rs.read_text()
    for f in abi["functions"]:
        if not re.search(rf"pub fn {f['name']}\s*\(", src):
            problems.append(f"ABI function `{f['name']}` not found in contract")
    return problems


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    abi = json.loads(ABI.read_text())
    if args.check:
        problems = drift(abi)
        for p in problems:
            print(f"DRIFT: {p}", file=sys.stderr)
        return 1 if problems else 0
    for rel, gen in TARGETS.items():
        (ROOT / rel).write_text(gen(abi))
        print(f"wrote {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
