#!/usr/bin/env python3
"""Contributor onboarding map (#542).

    python3 scripts/onboarding.py check                       # validate the map
    python3 scripts/onboarding.py recommend --interest rust --level beginner
    python3 scripts/onboarding.py refresh                     # rewrite docs/onboarding/live.md
    python3 scripts/onboarding.py outcomes                    # summarize outcomes.csv

Open issues are fetched live from the GitHub API (GITHUB_TOKEN optional, raises
the rate limit). Each issue is placed in an area by its `**Track:**` line and
labels, and ranked by its `**Difficulty:**` line. See docs/ONBOARDING.md.
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAP = ROOT / "docs" / "onboarding" / "map.json"
OUTCOMES = ROOT / "docs" / "onboarding" / "outcomes.csv"
LIVE = ROOT / "docs" / "onboarding" / "live.md"

LEVELS = {"beginner": 0, "intermediate": 1, "advanced": 2}
DIFFICULTY_RE = re.compile(r"Difficulty:\*\*\s*\S*\s*(Beginner|Easy|Intermediate|Advanced|Expert)", re.I)
TRACK_RE = re.compile(r"Track:\*\*\s*([^\n]+)")


def load_map(path: Path = MAP) -> dict:
    return json.loads(path.read_text())


def check_map(m: dict, root: Path = ROOT) -> list[str]:
    errors = []
    if not m.get("fallback_mentor"):
        errors.append("no fallback_mentor defined")
    seen = set()
    for a in m.get("areas", []):
        aid = a.get("id", "?")
        if aid in seen:
            errors.append(f"duplicate area id {aid}")
        seen.add(aid)
        for key in ("title", "track", "paths", "interests"):
            if not a.get(key):
                errors.append(f"area {aid}: missing {key}")
        for p in a.get("paths", []):
            if not (root / p).exists():
                errors.append(f"area {aid}: path {p} no longer exists")
    return errors


def difficulty(issue: dict) -> int:
    m = DIFFICULTY_RE.search(issue.get("body") or "")
    word = m.group(1).lower() if m else ""
    if word in ("beginner", "easy") or any(l == "good first issue" for l in labels(issue)):
        return 0
    return {"intermediate": 1, "advanced": 2, "expert": 2}.get(word, 1)


def labels(issue: dict) -> list[str]:
    return [l["name"] if isinstance(l, dict) else l for l in issue.get("labels", [])]


def area_of(issue: dict, m: dict) -> dict | None:
    t = TRACK_RE.search(issue.get("body") or "")
    track = t.group(1).strip() if t else ""
    for a in m["areas"]:
        if track and track.lower().startswith(a["track"].lower()):
            return a
    # No Track line: fall back to the first area claiming one of its labels.
    for a in m["areas"]:
        if set(a.get("labels", [])) & set(labels(issue)):
            return a
    return None


def mentor_for(area: dict, m: dict) -> str:
    return area["mentors"][0] if area.get("mentors") else m["fallback_mentor"]


def recommend(issues: list[dict], m: dict, interest: str | None, level: str, limit: int = 5) -> list[dict]:
    """Open, unassigned issues in areas matching `interest`, at or below `level`,
    easiest first. Documentation is not favoured: areas are matched only by interest."""
    cap = LEVELS[level]
    out = []
    for i in issues:
        if i.get("pull_request") or i.get("state", "open") != "open" or i.get("assignees"):
            continue
        a = area_of(i, m)
        if a is None or (interest and interest.lower() not in [x.lower() for x in a["interests"]]):
            continue
        d = difficulty(i)
        if d <= cap:
            out.append({"number": i["number"], "title": i["title"], "url": i.get("html_url", ""),
                        "area": a["id"], "difficulty": d, "mentor": mentor_for(a, m)})
    out.sort(key=lambda r: (r["difficulty"], r["number"]))
    return out[:limit]


def fetch_issues(repo: str) -> list[dict]:
    issues, page = [], 1
    headers = {"Accept": "application/vnd.github+json", "User-Agent": "onboarding-map"}
    if os.environ.get("GITHUB_TOKEN"):
        headers["Authorization"] = f"Bearer {os.environ['GITHUB_TOKEN']}"
    while True:
        url = f"https://api.github.com/repos/{repo}/issues?state=open&per_page=100&page={page}"
        with urllib.request.urlopen(urllib.request.Request(url, headers=headers), timeout=30) as r:
            batch = json.load(r)
        issues += batch
        if len(batch) < 100:
            return issues
        page += 1


def render_live(issues: list[dict], m: dict) -> str:
    lines = ["# Live onboarding map", "",
             "_Generated by `scripts/onboarding.py refresh`; do not edit by hand._", ""]
    for a in m["areas"]:
        mine = [i for i in issues if not i.get("pull_request") and area_of(i, m) is a]
        lines += [f"## {a['title']}", "", f"Mentor: {mentor_for(a, m)} · interests: {', '.join(a['interests'])}", ""]
        names = ["beginner", "intermediate", "advanced"]
        for i in sorted(mine, key=lambda i: (difficulty(i), i["number"])):
            lines.append(f"- [#{i['number']} {i['title']}]({i.get('html_url', '')}) — {names[difficulty(i)]}")
        if not mine:
            lines.append("- _no open issues right now_")
        lines.append("")
    return "\n".join(lines)


def summarize_outcomes(path: Path = OUTCOMES) -> dict:
    with open(path, newline="") as f:
        rows = list(csv.DictReader(f))
    merged = [r for r in rows if r.get("first_pr_merged")]
    return {"started": len(rows), "merged": len(merged),
            "conversion": round(len(merged) / len(rows), 2) if rows else None,
            "fallback_pairings": sum(1 for r in rows if r.get("mentor", "").endswith("/maintainers"))}


def main() -> int:
    p = argparse.ArgumentParser(description="Onboarding map")
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("check")
    r = sub.add_parser("recommend")
    r.add_argument("--interest")
    r.add_argument("--level", choices=LEVELS, default="beginner")
    sub.add_parser("refresh")
    sub.add_parser("outcomes")
    a = p.parse_args()
    m = load_map()
    if a.cmd == "check":
        errs = check_map(m)
        for e in errs:
            print(f"::error::{e}")
        print(f"onboarding map: {len(m['areas'])} areas, {len(errs)} problems")
        return 1 if errs else 0
    if a.cmd == "outcomes":
        print(json.dumps(summarize_outcomes(), indent=2))
        return 0
    issues = fetch_issues(m["repo"])
    if a.cmd == "recommend":
        for rec in recommend(issues, m, a.interest, a.level):
            print(f"#{rec['number']} [{rec['area']}] {rec['title']}  (mentor {rec['mentor']})\n    {rec['url']}")
        return 0
    LIVE.write_text(render_live(issues, m))
    print(f"wrote {LIVE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
